services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: pablo
      POSTGRES_PASSWORD: P4bl03011
      POSTGRES_DB: combinations_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
